package com.sinosoft.dto.insure;

import java.util.ArrayList;
import java.util.List;

public class StudentExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public StudentExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andSidIsNull() {
			addCriterion("Sid is null");
			return (Criteria) this;
		}

		public Criteria andSidIsNotNull() {
			addCriterion("Sid is not null");
			return (Criteria) this;
		}

		public Criteria andSidEqualTo(Integer value) {
			addCriterion("Sid =", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidNotEqualTo(Integer value) {
			addCriterion("Sid <>", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidGreaterThan(Integer value) {
			addCriterion("Sid >", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidGreaterThanOrEqualTo(Integer value) {
			addCriterion("Sid >=", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidLessThan(Integer value) {
			addCriterion("Sid <", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidLessThanOrEqualTo(Integer value) {
			addCriterion("Sid <=", value, "sid");
			return (Criteria) this;
		}

		public Criteria andSidIn(List<Integer> values) {
			addCriterion("Sid in", values, "sid");
			return (Criteria) this;
		}

		public Criteria andSidNotIn(List<Integer> values) {
			addCriterion("Sid not in", values, "sid");
			return (Criteria) this;
		}

		public Criteria andSidBetween(Integer value1, Integer value2) {
			addCriterion("Sid between", value1, value2, "sid");
			return (Criteria) this;
		}

		public Criteria andSidNotBetween(Integer value1, Integer value2) {
			addCriterion("Sid not between", value1, value2, "sid");
			return (Criteria) this;
		}

		public Criteria andCustomernoIsNull() {
			addCriterion("customerno is null");
			return (Criteria) this;
		}

		public Criteria andCustomernoIsNotNull() {
			addCriterion("customerno is not null");
			return (Criteria) this;
		}

		public Criteria andCustomernoEqualTo(String value) {
			addCriterion("customerno =", value, "customerno");
			return (Criteria) this;
		}

		public Criteria andCustomernoNotEqualTo(String value) {
			addCriterion("customerno <>", value, "customerno");
			return (Criteria) this;
		}

		public Criteria andCustomernoGreaterThan(String value) {
			addCriterion("customerno >", value, "customerno");
			return (Criteria) this;
		}

		public Criteria andCustomernoGreaterThanOrEqualTo(String value) {
			addCriterion("customerno >=", value, "customerno");
			return (Criteria) this;
		}

		public Criteria andCustomernoLessThan(String value) {
			addCriterion("customerno <", value, "customerno");
			return (Criteria) this;
		}

		public Criteria andCustomernoLessThanOrEqualTo(String value) {
			addCriterion("customerno <=", value, "customerno");
			return (Criteria) this;
		}

		public Criteria andCustomernoLike(String value) {
			addCriterion("customerno like", value, "customerno");
			return (Criteria) this;
		}

		public Criteria andCustomernoNotLike(String value) {
			addCriterion("customerno not like", value, "customerno");
			return (Criteria) this;
		}

		public Criteria andCustomernoIn(List<String> values) {
			addCriterion("customerno in", values, "customerno");
			return (Criteria) this;
		}

		public Criteria andCustomernoNotIn(List<String> values) {
			addCriterion("customerno not in", values, "customerno");
			return (Criteria) this;
		}

		public Criteria andCustomernoBetween(String value1, String value2) {
			addCriterion("customerno between", value1, value2, "customerno");
			return (Criteria) this;
		}

		public Criteria andCustomernoNotBetween(String value1, String value2) {
			addCriterion("customerno not between", value1, value2, "customerno");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andIdnoIsNull() {
			addCriterion("idno is null");
			return (Criteria) this;
		}

		public Criteria andIdnoIsNotNull() {
			addCriterion("idno is not null");
			return (Criteria) this;
		}

		public Criteria andIdnoEqualTo(String value) {
			addCriterion("idno =", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoNotEqualTo(String value) {
			addCriterion("idno <>", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoGreaterThan(String value) {
			addCriterion("idno >", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoGreaterThanOrEqualTo(String value) {
			addCriterion("idno >=", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoLessThan(String value) {
			addCriterion("idno <", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoLessThanOrEqualTo(String value) {
			addCriterion("idno <=", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoLike(String value) {
			addCriterion("idno like", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoNotLike(String value) {
			addCriterion("idno not like", value, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoIn(List<String> values) {
			addCriterion("idno in", values, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoNotIn(List<String> values) {
			addCriterion("idno not in", values, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoBetween(String value1, String value2) {
			addCriterion("idno between", value1, value2, "idno");
			return (Criteria) this;
		}

		public Criteria andIdnoNotBetween(String value1, String value2) {
			addCriterion("idno not between", value1, value2, "idno");
			return (Criteria) this;
		}

		public Criteria andCardnoIsNull() {
			addCriterion("cardno is null");
			return (Criteria) this;
		}

		public Criteria andCardnoIsNotNull() {
			addCriterion("cardno is not null");
			return (Criteria) this;
		}

		public Criteria andCardnoEqualTo(String value) {
			addCriterion("cardno =", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotEqualTo(String value) {
			addCriterion("cardno <>", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoGreaterThan(String value) {
			addCriterion("cardno >", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoGreaterThanOrEqualTo(String value) {
			addCriterion("cardno >=", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoLessThan(String value) {
			addCriterion("cardno <", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoLessThanOrEqualTo(String value) {
			addCriterion("cardno <=", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoLike(String value) {
			addCriterion("cardno like", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotLike(String value) {
			addCriterion("cardno not like", value, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoIn(List<String> values) {
			addCriterion("cardno in", values, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotIn(List<String> values) {
			addCriterion("cardno not in", values, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoBetween(String value1, String value2) {
			addCriterion("cardno between", value1, value2, "cardno");
			return (Criteria) this;
		}

		public Criteria andCardnoNotBetween(String value1, String value2) {
			addCriterion("cardno not between", value1, value2, "cardno");
			return (Criteria) this;
		}

		public Criteria andClassidIsNull() {
			addCriterion("classid is null");
			return (Criteria) this;
		}

		public Criteria andClassidIsNotNull() {
			addCriterion("classid is not null");
			return (Criteria) this;
		}

		public Criteria andClassidEqualTo(String value) {
			addCriterion("classid =", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidNotEqualTo(String value) {
			addCriterion("classid <>", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidGreaterThan(String value) {
			addCriterion("classid >", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidGreaterThanOrEqualTo(String value) {
			addCriterion("classid >=", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidLessThan(String value) {
			addCriterion("classid <", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidLessThanOrEqualTo(String value) {
			addCriterion("classid <=", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidLike(String value) {
			addCriterion("classid like", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidNotLike(String value) {
			addCriterion("classid not like", value, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidIn(List<String> values) {
			addCriterion("classid in", values, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidNotIn(List<String> values) {
			addCriterion("classid not in", values, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidBetween(String value1, String value2) {
			addCriterion("classid between", value1, value2, "classid");
			return (Criteria) this;
		}

		public Criteria andClassidNotBetween(String value1, String value2) {
			addCriterion("classid not between", value1, value2, "classid");
			return (Criteria) this;
		}

		public Criteria andOnworkIsNull() {
			addCriterion("onwork is null");
			return (Criteria) this;
		}

		public Criteria andOnworkIsNotNull() {
			addCriterion("onwork is not null");
			return (Criteria) this;
		}

		public Criteria andOnworkEqualTo(String value) {
			addCriterion("onwork =", value, "onwork");
			return (Criteria) this;
		}

		public Criteria andOnworkNotEqualTo(String value) {
			addCriterion("onwork <>", value, "onwork");
			return (Criteria) this;
		}

		public Criteria andOnworkGreaterThan(String value) {
			addCriterion("onwork >", value, "onwork");
			return (Criteria) this;
		}

		public Criteria andOnworkGreaterThanOrEqualTo(String value) {
			addCriterion("onwork >=", value, "onwork");
			return (Criteria) this;
		}

		public Criteria andOnworkLessThan(String value) {
			addCriterion("onwork <", value, "onwork");
			return (Criteria) this;
		}

		public Criteria andOnworkLessThanOrEqualTo(String value) {
			addCriterion("onwork <=", value, "onwork");
			return (Criteria) this;
		}

		public Criteria andOnworkLike(String value) {
			addCriterion("onwork like", value, "onwork");
			return (Criteria) this;
		}

		public Criteria andOnworkNotLike(String value) {
			addCriterion("onwork not like", value, "onwork");
			return (Criteria) this;
		}

		public Criteria andOnworkIn(List<String> values) {
			addCriterion("onwork in", values, "onwork");
			return (Criteria) this;
		}

		public Criteria andOnworkNotIn(List<String> values) {
			addCriterion("onwork not in", values, "onwork");
			return (Criteria) this;
		}

		public Criteria andOnworkBetween(String value1, String value2) {
			addCriterion("onwork between", value1, value2, "onwork");
			return (Criteria) this;
		}

		public Criteria andOnworkNotBetween(String value1, String value2) {
			addCriterion("onwork not between", value1, value2, "onwork");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table student
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table student
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 10 10:31:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}