package com.sinosoft.dto.insure;

public class Student {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.Sid
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	private Integer sid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.customerno
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	private String customerno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.name
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.idno
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	private String idno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.cardno
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	private String cardno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.classid
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	private String classid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column student.onwork
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	private String onwork;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.Sid
	 * @return  the value of student.Sid
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public Integer getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.Sid
	 * @param sid  the value for student.Sid
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public void setSid(Integer sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.customerno
	 * @return  the value of student.customerno
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public String getCustomerno() {
		return customerno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.customerno
	 * @param customerno  the value for student.customerno
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public void setCustomerno(String customerno) {
		this.customerno = customerno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.name
	 * @return  the value of student.name
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.name
	 * @param name  the value for student.name
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.idno
	 * @return  the value of student.idno
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public String getIdno() {
		return idno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.idno
	 * @param idno  the value for student.idno
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public void setIdno(String idno) {
		this.idno = idno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.cardno
	 * @return  the value of student.cardno
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public String getCardno() {
		return cardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.cardno
	 * @param cardno  the value for student.cardno
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public void setCardno(String cardno) {
		this.cardno = cardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.classid
	 * @return  the value of student.classid
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public String getClassid() {
		return classid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.classid
	 * @param classid  the value for student.classid
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public void setClassid(String classid) {
		this.classid = classid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column student.onwork
	 * @return  the value of student.onwork
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public String getOnwork() {
		return onwork;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column student.onwork
	 * @param onwork  the value for student.onwork
	 * @mbg.generated  Tue Jul 10 13:27:01 CST 2018
	 */
	public void setOnwork(String onwork) {
		this.onwork = onwork;
	}
}