package com.sinosoft.common.logservice.client.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.dto.log.Lkclienttranlog;
import com.sinosoft.dto.log.LkclienttranlogExample;
import com.sinosoft.dto.log.LkclienttranlogWithBLOBs;

public interface LkclienttranlogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int countByExample(LkclienttranlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int deleteByExample(LkclienttranlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int insert(LkclienttranlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int insertSelective(LkclienttranlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    List<LkclienttranlogWithBLOBs> selectByExampleWithBLOBs(LkclienttranlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    List<Lkclienttranlog> selectByExample(LkclienttranlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    LkclienttranlogWithBLOBs selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") LkclienttranlogWithBLOBs record, @Param("example") LkclienttranlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") LkclienttranlogWithBLOBs record, @Param("example") LkclienttranlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByExample(@Param("record") Lkclienttranlog record, @Param("example") LkclienttranlogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByPrimaryKeySelective(LkclienttranlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(LkclienttranlogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkclienttranlog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByPrimaryKey(Lkclienttranlog record);
}