package com.sinosoft.common.logservice.server.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.dto.log.LKservertranslog;
import com.sinosoft.dto.log.LKservertranslogExample;
import com.sinosoft.dto.log.LKservertranslogWithBLOBs;

public interface LKservertranslogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int countByExample(LKservertranslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int deleteByExample(LKservertranslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int insert(LKservertranslogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int insertSelective(LKservertranslogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    List<LKservertranslogWithBLOBs> selectByExampleWithBLOBs(LKservertranslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    List<LKservertranslog> selectByExample(LKservertranslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    LKservertranslogWithBLOBs selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") LKservertranslogWithBLOBs record, @Param("example") LKservertranslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") LKservertranslogWithBLOBs record, @Param("example") LKservertranslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByExample(@Param("record") LKservertranslog record, @Param("example") LKservertranslogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByPrimaryKeySelective(LKservertranslogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(LKservertranslogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lkservertranslog
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    int updateByPrimaryKey(LKservertranslog record);
}