package com.sinosoft.dto.log;

public class LkclienttranlogWithBLOBs extends Lkclienttranlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.requestContent
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private String requestcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.responseContent
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private String responsecontent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.requestContent
     *
     * @return the value of lkclienttranlog.requestContent
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public String getRequestcontent() {
        return requestcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.requestContent
     *
     * @param requestcontent the value for lkclienttranlog.requestContent
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setRequestcontent(String requestcontent) {
        this.requestcontent = requestcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.responseContent
     *
     * @return the value of lkclienttranlog.responseContent
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public String getResponsecontent() {
        return responsecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.responseContent
     *
     * @param responsecontent the value for lkclienttranlog.responseContent
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setResponsecontent(String responsecontent) {
        this.responsecontent = responsecontent;
    }
}