package com.sinosoft.dto.log;

import java.util.Date;

public class Lkclienttranlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.Sid
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.TranNo
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private String tranno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.sourceCode
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private String sourcecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.orderNo
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private String orderno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.businessType
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private String businesstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.Category
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.requestTime
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private Date requesttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.responseTime
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private Date responsetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.usedTime
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private Float usedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.state
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lkclienttranlog.makeDate
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    private Date makedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.Sid
     *
     * @return the value of lkclienttranlog.Sid
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.Sid
     *
     * @param sid the value for lkclienttranlog.Sid
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.TranNo
     *
     * @return the value of lkclienttranlog.TranNo
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public String getTranno() {
        return tranno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.TranNo
     *
     * @param tranno the value for lkclienttranlog.TranNo
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setTranno(String tranno) {
        this.tranno = tranno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.sourceCode
     *
     * @return the value of lkclienttranlog.sourceCode
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public String getSourcecode() {
        return sourcecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.sourceCode
     *
     * @param sourcecode the value for lkclienttranlog.sourceCode
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setSourcecode(String sourcecode) {
        this.sourcecode = sourcecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.orderNo
     *
     * @return the value of lkclienttranlog.orderNo
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public String getOrderno() {
        return orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.orderNo
     *
     * @param orderno the value for lkclienttranlog.orderNo
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setOrderno(String orderno) {
        this.orderno = orderno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.businessType
     *
     * @return the value of lkclienttranlog.businessType
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public String getBusinesstype() {
        return businesstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.businessType
     *
     * @param businesstype the value for lkclienttranlog.businessType
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setBusinesstype(String businesstype) {
        this.businesstype = businesstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.Category
     *
     * @return the value of lkclienttranlog.Category
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.Category
     *
     * @param category the value for lkclienttranlog.Category
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.requestTime
     *
     * @return the value of lkclienttranlog.requestTime
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public Date getRequesttime() {
        return requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.requestTime
     *
     * @param requesttime the value for lkclienttranlog.requestTime
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setRequesttime(Date requesttime) {
        this.requesttime = requesttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.responseTime
     *
     * @return the value of lkclienttranlog.responseTime
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public Date getResponsetime() {
        return responsetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.responseTime
     *
     * @param responsetime the value for lkclienttranlog.responseTime
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setResponsetime(Date responsetime) {
        this.responsetime = responsetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.usedTime
     *
     * @return the value of lkclienttranlog.usedTime
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public Float getUsedtime() {
        return usedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.usedTime
     *
     * @param usedtime the value for lkclienttranlog.usedTime
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setUsedtime(Float usedtime) {
        this.usedtime = usedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.state
     *
     * @return the value of lkclienttranlog.state
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.state
     *
     * @param state the value for lkclienttranlog.state
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lkclienttranlog.makeDate
     *
     * @return the value of lkclienttranlog.makeDate
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public Date getMakedate() {
        return makedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lkclienttranlog.makeDate
     *
     * @param makedate the value for lkclienttranlog.makeDate
     *
     * @mbggenerated Fri Jun 23 09:33:22 CST 2017
     */
    public void setMakedate(Date makedate) {
        this.makedate = makedate;
    }
}